# Generated by Django 5.1 on 2024-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_or_dislike',
            field=models.CharField(choices=[('👍🏻', '👍🏻'), ('👎🏻', '👎🏻')], max_length=100, null=True),
        ),
    ]
