# Generated by Django 5.1 on 2024-09-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_like_or_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_post', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_post', to='blog.post')),
            ],
        ),
    ]
